language: java
sudo: true
jdk:
  - openjdk11

before_install:
  - chmod +x mvnw
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:11-jre-slim-sid

deploy:
 provider: heroku
 api-key: 
  secure: $HEROKU_API_KEY
 app: $APP
 on:
    branch: main

#script:  
#  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install
#  - ./mvnw heroku:deploy jib:build -P deploy-heroku,deploy-docker

#after_success:
#  - bash <(curl -s https://codecov.io/bash)
